CREATE TABLE cidade (
	codigo SERIAL PRIMARY KEY,
	nome VARCHAR(30) NOT NULL,
	estado VARCHAR(20) NOT NULL,
	populacao INT NOT NULL
);

CREATE TABLE Ponto_turistico(
	cod_pt INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 1000 INCREMENT BY 1),
	cod_cid INT,
	FOREIGN KEY(cod_cid) REFERENCES cidade(codigo)
);

CREATE TABLE Igreja(
	cod_igreja INT GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 2000 INCREMENT BY 1),
	cod_pt INT,
	estilo VARCHAR(30),
	desc_igreja TEXT NULL,
	data_const DATE ,
	PRIMARY KEY(cod_igreja),
	FOREIGN KEY(cod_pt)REFERENCES Ponto_turistico(cod_pt)
);

CREATE TABLE end_igreja(
	cod_igreja INT PRIMARY KEY,
	rua VARCHAR(50),
	bairro VARCHAR(50),
	numero INT,
	FOREIGN KEY(cod_igreja) REFERENCES Igreja(cod_igreja)
);

CREATE TABLE Museu(
	cod_museu INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 3000 INCREMENT BY 1),
	cod_pt INT,
	data_fundacao DATE NOT NULL,
	num_salas SMALLINT,
	desc_museu TEXT NULL,
	FOREIGN KEY(cod_pt)REFERENCES Ponto_turistico(cod_pt)
);

CREATE TABLE end_museu(
	cod_museu INT PRIMARY KEY,
	rua VARCHAR(50),
	bairro VARCHAR(50),
	numero INT,
	FOREIGN KEY(cod_museu) REFERENCES Museu(cod_museu)
);
CREATE TABLE Fundador(
	cod_fundador INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 9000 INCREMENT BY 1),
	nacionalidade VARCHAR(40),
	nome VARCHAR(50) NOT NULL,
	data_nasc DATE NOT NULL,
	data_morte DATE NOT NULL,
	atv_profissional  TEXT
);
CREATE TABLE Igreja_fundada_por_Fundador(
	cod_museu INT,
	cod_fundador INT,
	FOREIGN KEY(cod_museu)REFERENCES Museu(cod_museu),
	FOREIGN KEY(cod_fundador)REFERENCES Fundador(cod_fundador)
);

CREATE TABLE Casa_de_show(
	cod_show INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 4000 INCREMENT BY 1),
	cod_rest INT,
	hora_abertura TIME,
	dia_fechamente VARCHAR(20),
	descricao TEXT NULL,
	cod_pt INT,
	FOREIGN KEY(cod_pt)REFERENCES Ponto_turistico(cod_pt),
	FOREIGN KEY(cod_rest) REFERENCES Restaurante(cod_rest)
);
CREATE TABLE end_show(
	cod_show INT PRIMARY KEY,
	rua VARCHAR(50),
	bairro VARCHAR(50),
	numero INT,
	FOREIGN KEY(cod_show) REFERENCES Casa_de_show(cod_show)
);

CREATE TABLE Restaurante(
	cod_rest INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 5000 INCREMENT BY 1),
	nome VARCHAR(50) NOT NULL,
	categoria VARCHAR(30),
	especialidade VARCHAR(50),
	preco_medio NUMERIC CHECK(preco_medio>0) NOT NULL,
	cod_cid INT,
	FOREIGN KEY(cod_cid) REFERENCES Cidade(codigo)
);
CREATE TABLE end_rest(
	cod_rest INT PRIMARY KEY,
	rua VARCHAR(50),
	bairro VARCHAR(50),
	numero INT,
	FOREIGN KEY(cod_rest) REFERENCES Restaurante(cod_rest)
);

CREATE TABLE Hotel(
	cod_hotel INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 6000 INCREMENT BY 1),
	nome VARCHAR(50) NOT NULL,
	categoria VARCHAR(30),
	cod_cid INT,
	cod_rest INT,
	FOREIGN KEY(cod_cid) REFERENCES Cidade(codigo),
	FOREIGN KEY(cod_rest) REFERENCES Restaurante(cod_rest)
);
CREATE TABLE end_hotel(
	cod_hotel INT PRIMARY KEY,
	rua VARCHAR(50),
	bairro VARCHAR(50),
	numero INT,
	FOREIGN KEY(cod_hotel) REFERENCES Hotel(cod_hotel)
);
CREATE TABLE Quarto(
	num_quarto INT PRIMARY KEY,
	valor_diaria NUMERIC CHECK(valor_diaria > 0) NOTNULL,
	tipo_quarto VARCHAR(20),
	cod_hotel INT,
	FOREIGN KEY (cod_hotel) REFERENCES Hotel(cod_hotel)
);
